spring:
  application:
    name: notes-calculation

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    username: adm
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/home/daianepereira/db-test

  jpa:
    hibernate:
      ddl-auto: update